//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppClient.ThirdPartySvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThirdPartyCmd", Namespace="http://schemas.datacontract.org/2004/07/CommandServer.Messages.Commands")]
    [System.SerializableAttribute()]
    public partial class ThirdPartyCmd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents {
            get {
                return this.ContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentsField, value) != true)) {
                    this.ContentsField = value;
                    this.RaisePropertyChanged("Contents");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThirdPartyCmdResponse", Namespace="http://schemas.datacontract.org/2004/07/CommandServer.Messages.Commands")]
    public enum ThirdPartyCmdResponse : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nservicebus.com", ConfigurationName="ThirdPartySvc.IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse")]
    public interface IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nservicebus.com/IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse/Process", ReplyAction="http://nservicebus.com/IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse/ProcessR" +
            "esponse")]
        ConsoleAppClient.ThirdPartySvc.ThirdPartyCmdResponse Process(ConsoleAppClient.ThirdPartySvc.ThirdPartyCmd request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseChannel : ConsoleAppClient.ThirdPartySvc.IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient : System.ServiceModel.ClientBase<ConsoleAppClient.ThirdPartySvc.IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse>, ConsoleAppClient.ThirdPartySvc.IWcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponse {
        
        public WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient() {
        }
        
        public WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_ThirdPartyCmd_ThirdPartyCmdResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppClient.ThirdPartySvc.ThirdPartyCmdResponse Process(ConsoleAppClient.ThirdPartySvc.ThirdPartyCmd request) {
            return base.Channel.Process(request);
        }
    }
}
